{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "duvora.secretName" . }}
  labels:
    {{- include "duvora.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-password: {{ required "auth.adminPassword is required" .Values.auth.adminPassword | quote }}
  {{- with .Values.auth.keys }}
  keys.json: {{ . | quote }}
  {{- end }}
{{- end }}
{{- if and .Values.netra.url (not .Values.netra.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "duvora.name" . }}-netra
  labels:
    {{- include "duvora.labels" . | nindent 4 }}
type: Opaque
stringData:
  netra-api-key: {{ required "netra.apiKey is required when netra.url is set" .Values.netra.apiKey | quote }}
  {{- with .Values.netra.caCert }}
  netra-ca.crt: {{ . | quote }}
  {{- end }}
{{- end }}
{{- if and .Values.tls.enabled (not .Values.tls.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "duvora.tlsSecretName" . }}
  labels:
    {{- include "duvora.labels" . | nindent 4 }}
type: kubernetes.io/tls
stringData:
  tls.crt: {{ required "tls.cert is required when tls.enabled" .Values.tls.cert | quote }}
  tls.key: {{ required "tls.key is required when tls.enabled" .Values.tls.key | quote }}
{{- end }}
